import { AlertTriangle, Brain, ShieldCheck, Sparkles, Stethoscope, UserRound } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { StatusBadge } from './StatusBadge'
import { Progress } from '@/components/ui/progress'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import type { AIAssessmentResult } from '@/types'

export function AIResultCard({
  result,
  onRequestReview,
  onRestart,
  reviewMode,
}: {
  result: AIAssessmentResult
  onRequestReview?: () => void
  onRestart?: () => void
  reviewMode?: boolean
}) {
  const topCondition = result.possibleConditions[0]
  const urgencyColor = result.urgency === 'Urgent' ? 'text-destructive' : result.urgency === 'Moderate' ? 'text-warning' : 'text-success'

  return (
    <Card className={cn('overflow-hidden', 'border-primary/25 shadow-lift')}>
      <div className="flex items-center gap-2 bg-gradient-to-r from-primary to-[#7E51CE] px-5 py-3 text-white">
        <Brain className="h-5 w-5" />
        <div>
          <p className="font-display text-sm font-bold tracking-wide">AI-ASSISTED PRELIMINARY ASSESSMENT</p>
          <p className="text-[11px] text-white/75">Generated by MEDAI Diagnostic Engine · Not a confirmed diagnosis</p>
        </div>
      </div>

      <CardContent className="p-5">
        <div className="flex flex-wrap items-center gap-2">
          <StatusBadge tone={result.urgency} />
          <StatusBadge tone={result.risk} />
          <span className="ml-auto text-xs font-medium text-muted-foreground">{new Date(result.createdAt).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</span>
        </div>

        <div className="mt-4 rounded-xl bg-secondary/60 p-4">
          <p className="flex items-center gap-1.5 text-xs font-semibold uppercase tracking-wide text-primary">
            <Sparkles className="h-3.5 w-3.5" /> Possible condition
          </p>
          <p className="mt-1 font-display text-xl font-bold">{topCondition.name}</p>
          <div className="mt-3">
            <div className="flex items-center justify-between text-xs">
              <span className="text-muted-foreground">Model confidence</span>
              <span className="font-bold">{topCondition.confidence}%</span>
            </div>
            <Progress value={topCondition.confidence} className="mt-1.5 h-2" />
          </div>
        </div>

        <div className="mt-4 grid grid-cols-2 gap-3 text-center">
          <div className="rounded-xl border p-3">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Urgency</p>
            <p className={cn('mt-1 font-display text-lg font-bold', urgencyColor)}>{result.urgency}</p>
          </div>
          <div className="rounded-xl border p-3">
            <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">Recommendation</p>
            <p className="mt-1 text-xs font-medium leading-snug">{result.recommendation}</p>
          </div>
        </div>

        <p className="mt-4 text-sm text-muted-foreground">{result.summary}</p>

        {result.possibleConditions.length > 1 && (
          <div className="mt-4 space-y-1.5">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Other possibilities</p>
            {result.possibleConditions.slice(1).map((c) => (
              <div key={c.name} className="flex items-center justify-between rounded-lg border px-3 py-2 text-xs">
                <span>{c.name}</span>
                <span className="font-semibold text-muted-foreground">{c.confidence}%</span>
              </div>
            ))}
          </div>
        )}

        <div className="mt-4 flex items-start gap-2 rounded-lg bg-warning/10 p-3 text-xs text-foreground">
          <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-warning" />
          <p className="leading-relaxed">{result.disclaimer}</p>
        </div>

        <div className="mt-4 flex flex-wrap gap-2">
          {onRequestReview && !reviewMode && (
            <Button size="sm" onClick={onRequestReview}>
              <Stethoscope className="mr-1" /> Request Medical Review
            </Button>
          )}
          {onRestart && (
            <Button size="sm" variant="outline" onClick={onRestart}>
              Start New Assessment
            </Button>
          )}
          {reviewMode && (
            <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-success">
              <ShieldCheck className="h-4 w-4" /> Awaiting clinician review
            </span>
          )}
        </div>

        <div className="mt-4 flex items-center gap-1.5 border-t pt-3 text-[11px] text-muted-foreground">
          <UserRound className="h-3 w-3" /> Vitals used: HR {result.vitalsUsed.heartRate} BPM · SpO₂ {result.vitalsUsed.spo2}% · Temp {result.vitalsUsed.temperature}°C
        </div>
      </CardContent>
    </Card>
  )
}
