import { Link } from 'react-router-dom'
import { AlertTriangle, ArrowRight, BrainCircuit, CheckCircle2, Stethoscope, Timer } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { PageHero, SectionHeading } from '@/components/shared/PublicSections'
import { AIResultCard } from '@/components/shared/AIResultCard'
import { Stepper } from '@/components/shared/Stepper'
import type { AIAssessmentResult } from '@/types'

const demoResult: AIAssessmentResult = {
  id: 'demo',
  patientId: 'pat_1',
  possibleConditions: [
    { name: 'Respiratory infection', probability: 0.82, confidence: 82, description: 'Viral or bacterial infection affecting the airways.' },
    { name: 'Allergic rhinitis', probability: 0.14, confidence: 14, description: 'Allergen-driven upper airway response.' },
    { name: 'Influenza-like illness', probability: 0.04, confidence: 4, description: 'Systemic viral infection.' },
  ],
  confidence: 82,
  urgency: 'Moderate',
  risk: 'Moderate',
  summary: 'Fever, cough and fatigue combined with borderline SpO₂ suggest an acute respiratory tract infection.',
  recommendation: 'Consult a healthcare professional. Monitor SpO₂ and stay hydrated.',
  symptoms: ['Fever', 'Cough', 'Fatigue'],
  duration: '3 days',
  vitalsUsed: { heartRate: 84, spo2: 96, temperature: 37.9 },
  disclaimer: 'AI-ASSISTED PRELIMINARY ASSESSMENT — This result is generated by an AI model for triage support only. It is not a medical diagnosis and does not replace professional clinical judgement.',
  createdAt: new Date().toISOString(),
  status: 'Pending Review',
}

const steps = [
  { label: 'Symptoms' },
  { label: 'Health Info' },
  { label: 'IoT Data' },
  { label: 'AI Processing' },
  { label: 'Preliminary Assessment' },
  { label: 'Doctor Review' },
]

export default function PublicAIAssessment() {
  return (
    <div>
      <PageHero
        eyebrow="AI Assessment"
        title="AI-assisted triage, reviewed by humans"
        subtitle="A six-step workflow: symptoms, health information, IoT data, AI processing, preliminary assessment, then doctor review."
      />

      <section className="mx-auto max-w-6xl px-4 py-16 md:px-6">
        <div className="rounded-2xl border bg-card p-8 shadow-card">
          <Stepper steps={steps} current={2} />
        </div>
      </section>

      <section className="border-y bg-card/50">
        <div className="mx-auto max-w-6xl px-4 py-16 md:px-6">
          <SectionHeading center eyebrow="Example output" title="What the patient sees" subtitle="Always the AI-ASSISTED PRELIMINARY ASSESSMENT label. Always a route to medical review." />
          <div className="mx-auto max-w-2xl">
            <AIResultCard result={demoResult} />
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-16 md:px-6">
        <div className="grid gap-5 md:grid-cols-3">
          {[
            { icon: BrainCircuit, title: 'What the AI does', body: 'Combines symptoms, duration, demographics and live IoT vitals against clinical decision patterns to score possible conditions.' },
            { icon: AlertTriangle, title: 'What the AI never does', body: 'It never claims certainty, never bypasses a clinician, and never stores anything without consent and audit.' },
            { icon: CheckCircle2, title: 'What happens after', body: 'The preliminary assessment is queued for a named clinician who confirms, adjusts or dismisses it into the permanent record.' },
          ].map((c) => (
            <div key={c.title} className="rounded-xl border bg-card p-6 shadow-card">
              <div className="grid h-11 w-11 place-items-center rounded-lg bg-primary/10 text-primary"><c.icon className="h-5 w-5" /></div>
              <h3 className="mt-4 font-display text-base font-bold">{c.title}</h3>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{c.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 rounded-2xl border border-warning/30 bg-warning/5 p-6 text-center">
          <div className="flex items-center justify-center gap-2 text-sm font-semibold">
            <Timer className="h-4 w-4 text-warning" /> Typical AI processing time: ~2 seconds
          </div>
          <p className="mt-2 text-sm text-muted-foreground">Human review is the step that cannot be skipped. MEDAI assists healthcare professionals — it does not replace doctors.</p>
          <div className="mt-5 flex flex-wrap justify-center gap-3">
            <Button asChild><Link to="/register">Run a demo assessment <ArrowRight /></Link></Button>
            <Button variant="outline" asChild><Link to="/login">Sign in as a patient</Link></Button>
          </div>
        </div>
      </section>
    </div>
  )
}
